Corrected combine_restarts from load fre-nctools module
the fre-nctools module no longer exists, However, the combine_restarts
application still looked for it.  This update now verifies all required
applications are in PATH, if not exits.

Also corrected a few non-POSIX standard use of "[[ .. ]]".

diff --git a/postprocessing/combine_restarts/combine_restarts b/postprocessing/combine_restarts/combine_restarts
--- a/postprocessing/combine_restarts/combine_restarts
+++ b/postprocessing/combine_restarts/combine_restarts
@@ -40,12 +40,21 @@ while getopts :hv OPT; do
     esac
 done
 
-# Determine if fre-nctools is loaded.  If not, load the default version
-which is-compressed > /dev/null 2>&1
-if [[ $? -ne 0 ]]; then
-    echo "FRE NC Tools module not loaded.  Loading the default version"
-    module load fre-nctools
-fi
+# Determine if the required commands are available, if not exit.  As
+# all of these commands are part of FRE, usually if one is missing
+# all are missing.
+reqCommands="is-compressed \
+             combine-ncc \
+             mppnccombine"
+for c in $reqCommands
+do
+  command -v ${c} > /dev/null 2>&1
+  if [ $? -ne 0 ]
+  then
+    echo "Required application \"${c}\" is not in PATH.  Is the FRE module loaded" >&2
+    exit 1
+  fi
+done
 
 # Grep patterens needed
 patternGrepTail='\.[0-9]{4}$'
@@ -65,14 +74,14 @@ mppCombOpts='-64 -h 16384 -m'
 
 for f in ${restartFiles}
 do
-    if [[ ${verbose} -gt 0 ]]; then
+    if [ ${verbose} -gt 0 ]; then
 	echo ${f}
     fi
     inputFiles=$( ls -1 | egrep "${f}${patternGrepTail}" )
-    if [[ $( echo ${inputFiles} | wc -w ) -gt 0 ]]; then
+    if [ $( echo ${inputFiles} | wc -w ) -gt 0 ]; then
 	# Check if file is a compressed file
 	is-compressed $( echo ${inputFiles} | cut -d ' ' -f 1 )
-	if [[ $? -eq 0 ]]; then
+	if [ $? -eq 0 ]; then
 	    # File is compressed
 	    if [[ ${verbose} -gt 1 ]]; then
 		echo "combine-ncc ${inputFiles} ${f}"
@@ -85,10 +94,10 @@ do
 		\rm -f ${inputFiles}
 	    fi
 	else
-	    if [[ -e ${f} ]]; then
+	    if [ -e ${f} ]; then
 		\rm -f ${f}
 	    fi
-	    if [[ ${verbose} -gt 1 ]]; then
+	    if [ ${verbose} -gt 1 ]; then
 		echo "mppnccombine $mppCombOpts ${f} ${inputFiles}"
 	    fi
 	    mppnccombine $mppCombOpts ${f} ${inputFiles}
